version: '3.8'
networks:
  dev:

services:
  db:
    image: postgres
    env_file:
      - ./src/docker.env
    ports:
      - 6000:5432
    volumes:
    - short_url_db_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:  # указание глобального тома где-то в папках докера, чтобы не мозолила глаза
  short_url_db_data:

